name: Action Smoke Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - action-smoke-test

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Print status
        run: echo "actions are running"
